### ISSUE TITLE
consider swapping the action & state parameters

### ISSUE THREAD

**Issue by frankwallis** [reasonml-community/reductive#19]
see https://github.com/reasonml/reason-react/issues/62

If this is going to be the redux implementation for reason then it would make sense if the reducer parameters match those of reducerComponent to make it easier to pull reducers out of components and into global state.

I understand the advice that this library may not be necessary but IMHO pulling state out of components and into a global state tree is important to help applications scale.

If agreed, I am happy to send a PR..

**Comment by rickyvetter** [comment]
I'm conflicted about this. reductive doesn't have the same async constraints that React fiber reducers do. There also isn't a huge advantage to the swap since they still would require a refactor. Reason React reducers are of type `'action => 'state => update 'state 'sideEffects` and reductive, if this change were made, would be of type `'action => 'state => 'state`. Right now I don't think change is worth breaking the api and deviating from redux.

I would definitely support explorations of matching the api exactly though - meaning trying to get reductive reducer api to be of type `'action => 'state => ReasonReact.update 'state 'sideEffects`. I'm not confident we would want to make that change, but it would certainly be interesting.

**Comment by frankwallis** [comment]
I did not realise that the component reducers allow you to return side-effects, I think it would be amazing if reductive also supported this as it is a 'missing piece' in Redux.

I have a use case in mind for this - my application displays a list of 'growl' notifications which are held  in the central state and managed by a reducer with a ```Notify``` action and a ```Dismiss``` action. I would like the notifications to timeout, so that they automatically disappear after 10 seconds. Currently I have to use a thunk action which dispatches the ```Notify``` action and then does a ```setTimeout```. I think this could be handled by the ```Notify``` action returning a side-effect from the reducer.

The ReasonReact component reducers return this:
```
/* Control how a state update is performed.
   The state can be updated of left unchanged.
   Side effects can be specified and are scheduled for later execution.
   Note: when a side effect is scheduled, it's added to a queue of existing pending side effects.
   All the side effects are performed in batch after all the state updates have been performed,
   in the same order in which they were scheduled, just before shouldUpdate is called. */
type update 'state 'retainedProps 'action =
  /* Don't update the state. */
  | NoUpdate
  /* Update the state with the given one. */
  | Update 'state
  /* Update the state with the given one, but don't trigger a re-render.
     Do not prevent a re-render either, if one was scheduled to happen. */
  | SilentUpdate 'state
  /* Perform side effects without updating state, and don't trigger a re-render.
     Do not prevent a re-render either, if one was scheduled to happen.
     The side effects function is invoked when all the updates have completed. */
  | SideEffects (self 'state 'retainedProps 'action => unit)
  /* Update the state and perform side effects.
     The side effects function is invoked when all the updates have completed. */
  | UpdateWithSideEffects 'state (self 'state 'retainedProps 'action => unit)
  /* Like UpdateWithSideEffects, but don't trigger a re-render.
     Do not prevent a re-render either, if one was scheduled to happen. */
  | SilentUpdateWithSideEffects 'state (self 'state 'retainedProps 'action => unit)
```
I am not sure that the reductive reducers will be able to match this exactly - what will 'self' and 'retainedProps' be for example? So it may be necessary to just use a cutdown version of the above?

The side-effects will also need access to ```dispatch``` - perhaps the side-effects themselves should be dispatchable ie. a thunk or a plain action?

**Comment by rickyvetter** [comment]
Yeah modeling after the reason-react API with `UpdateWithSideEffects 'state (Store.t 'action 'state)` makes sense to me. It's a pretty big change from the current API and deviates from redux much more than I was anticipating.

I think I'd rather see reason-react stores as another library. This one should be familiar to redux users and can point to better alternatives if we think there is one.
