### ISSUE TITLE
Additional Documentation 

### ISSUE THREAD

**Issue by AaronVasquez** [reasonml-community/reductive#21]
The docs say that this library isn't needed since Reason has good enough construction blocks out of the box. Is there a sample project I can see where the redux architecture is done using ReasonML construction blocks? It would be helpful to also include this in the docs.

**Comment by chenglou** [comment]
Hey. ReasonReact comes with reducers out of the box: https://github.com/reasonml-community/reductive#word-of-caution

We encourage local state management. It's much more performant and contains basically no layers of indirections. This library was set up as a demonstration of what redux would look like in Reason, but, just like with Elm, it's only a demo and isn't really used.

Please do take a look at local state management with RR reducers! Thanks.
