### ISSUE TITLE
Update to JSX v3 to support BuckleScript 8

### ISSUE THREAD

**Issue by thislogancall** [reasonml-community/reductive#60]
Are there any plans or current progress on updating reductive to use jsx v3 so that it will compile with BuckleScript v8?

**Comment by rolandpeelen** [comment]
+1 on this

**Comment by rolandpeelen** [comment]
@rickyvetter - Thanks for merging my PR. Would you also be able to draft a release? I'd be happy to do it myself as well, but then I'd need to become a collaborator :)

**Comment by rolandpeelen** [comment]
@rickyvetter -- Gentle reminder that the release still needs to happen, technically, this issue hasn't been resolved ;)
